name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
        - target: "aarch64-unknown-linux-musl"
          linker: "aarch64-linux-gnu-gcc"
          dependencies: "crossbuild-essential-arm64"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: sudo apt-get -qq install ${{ matrix.dependencies }}
      - name: Install target
        run: rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
      - name: Build (release)
        run: cargo build --target ${{ matrix.target }} --config target.${{ matrix.target }}.linker=\"${{ matrix.linker }}\" --release

